version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/ai-counting-cranes-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
